booklist/urls.py
from django.urls import path
from booklist.views import get_books, show_booklist, add_book_ajax, delete_book_ajax, create_book_flutter, delete_book_flutter
app_name = 'booklist'

urlpatterns = [
    path("api/buku/", get_books, name="get_books"),
    path("", show_booklist, name="show_booklist"),
    path("add-book-ajax/", add_book_ajax, name="add_book_ajax"),
    path("delete-book-ajax/", delete_book_ajax, name="delete_book_ajax"),
    path("create-book-flutter/", create_book_flutter, name="create_book_flutter"),
    path("delete-book-flutter/", delete_book_flutter, name="delete_book_flutter"),
]

bookrequest/urls.py
from django.urls import path
from bookrequest.views import get_books, add_books, show_request, approve_request, get_books_individual, delete_request_ajax_individual, like_request_ajax, delete_request_ajax, delete_request_flutter, like_request_flutter, approve_request_flutter, create_request_flutter, get_books_individual_flutter
app_name = 'bookrequest'

urlpatterns = [
    path('get_books_individual_flutter', get_books_individual_flutter, name='get_books_individual_flutter'),
    path('create_request_flutter', create_request_flutter, name='create_request_flutter'),
    path('approve_request_flutter', approve_request_flutter, name='approve_request_flutter'),
    path('like_request_flutter', like_request_flutter, name='like_request_flutter'),
    path('delete_request_flutter', delete_request_flutter, name='delete_request_flutter'),
    path('like_request_ajax', like_request_ajax, name='like_request_ajax'),
    path('approve_request', approve_request, name='approve_request'),
    path("", show_request, name="show_request"),
    path("get_books_individual", get_books_individual, name="get_books_individual"),
    path("get_books", get_books, name="get_books"),
    path("add_books", add_books, name="add_books"),
    path('delete-request-ajax-individual/<int:id>/', delete_request_ajax_individual, name='delete_request_ajax_individual'),
    path('delete-request-ajax', delete_request_ajax, name='delete_request_ajax'),
]

main/urls.py
from django.urls import path
from main.views import *
from ordernborrow.views import *


app_name = 'main'


urlpatterns = [
    path('', show_main, name='show_main'),
    path('signup/', signup, name='signup'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'), 
]

ordernborrow/urls.py
from django.urls import path
from ordernborrow.views import *

app_name = 'ordernborrow'

urlpatterns = [
    path('guest/food/', food_view, name='food_menu'),
    path('guest/drinks/', drinks_view, name='drinks_menu'),
    path('guest/order/', order_food_ajax, name='order_food_ajax'),
    path('guest/order-summary/', show_order_guest, name="show_order_guest"),
    path('guest/get-product/', get_product_json, name='get_product_json'),
    path('guest/delete-order-ajax/<int:id>/', delete_order_ajax, name='delete_order_ajax'),
    path('guest/delete-all-order-ajax/', delete_allorder_ajax, name='delete_allorder_ajax'),
    path('guest/edit-order-ajax/<int:id>/', edit_order_ajax, name='edit_order_ajax'),

    path('member/food', food_view_member, name='food_menu_member'),
    path('member/drinks', drinks_view_member, name='drinks_menu_member'),
    path('member/order/', order_food_ajax_member, name='order_food_ajax_member'),
    path('member/secret-menu', secret_menu_view, name='secret_menu_view'),
    path('member/order-summary/', show_order_member, name="show_order_member"),
    path('member/get-product/', get_product_json_member, name='get_product_json_member'),
    path('member/delete-order-ajax/<int:id>/', delete_order_ajax_member, name='delete_order_ajax_member'),
    path('member/delete-all-order-ajax/', delete_allorder_ajax_member, name='delete_allorder_ajax_member'),
    path('member/edit-order-ajax/<int:id>/', edit_order_ajax_member, name='edit_order_ajax_member'),

    path('member/borrow/', show_books, name='show_books'),
    path('member/show-borrowed/', show_borrowed_books, name='show_borrowed_books'),
    path('member/borrow-book/', borrow_book_member, name='borrow_book_member'),
    path('member/return-book/<int:id>/', return_book_member, name='return_book_member'),
    path('member/borrowed/', show_json_borrowedbooks, name='show_json_borrowedbooks'),
    path('member/borrowed-history/', show_json_borrowedhistory, name='show_json_borrowedhistory'),
    path('member/show-borrowed-history/', show_borrowed_history, name='show_borrowed_history'),
    path('member/create-borrowed-history/', create_borrowed_history, name='create_borrowed_history'),

    path('employee/supplies-equipment/', supplies_and_equipment_view, name='supplies_and_equipment_view'),

    path('api/get-food/', get_food, name="get_food"),
    path('api/get-drink/', get_drink, name="get_drink"),
    path('guest/order-drink-flutter/', create_order_flutter, name="order_drink"),
    path('guest/order-food-flutter/', create_order_flutter, name="order_food"),
    path('guest/delete-all-order-flutter/', delete_allorder_flutter, name='delete_allorder_flutter'),
    path('guest/edit-order-flutter/<int:id>/', edit_order_flutter, name='edit_order_flutter'),
    path('guest/delete-order-flutter/<int:id>/', delete_order_flutter, name='delete_order_flutter'),

    path('member/order-drink-flutter/', create_order_member_flutter, name="order_drink_member"),
    path('member/order-food-flutter/', create_order_member_flutter, name="order_food_member"),
    path('member/get-product-flutter/', get_product_flutter_member, name="get_product_flutter_member"),
    path('member/delete-all-order-flutter/', delete_allorder_member_flutter, name="delete_allorder_member_flutter"),
    path('member/edit-order-flutter/<int:id>/', edit_order_member_flutter, name="edit_order_member_flutter"),
    path('member/delete-order-flutter/<int:id>/', delete_order_member_flutter, name="delete_order_member_flutter"),

    path('member/borrow-book-flutter/', borrow_book_flutter, name='borrow_book_flutter'),
    path('member/return-book-flutter/', return_book_flutter, name='return_book_flutter'),
]

read_and_brew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booklist/', include('booklist.urls')),
    path('ordernborrow/', include('ordernborrow.urls')),
    path('reviewmodul/', include('reviewmodul.urls')),
    path('trackernplanner/', include('trackernplanner.urls')),
    path('bookrequest/', include('bookrequest.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

reviewmodul/urls.py
from django.urls import path
from reviewmodul.views import *

app_name = 'reviewmodul'

urlpatterns = [
    path('show_review/', show_review, name='show_review'),
    path('add_review_ajax/', add_review_ajax, name='add_review_ajax'),
    path('get-review/', get_review_json, name='get_review_json'),
    path('get-review-member/', get_review_json_member, name='get_review_json_member'),
    path('show_review/delete_review/<int:id>/', delete_review, name='delete_review'),
    path('get_borrowed_history_json_member', get_borrowed_history_json_member, name='get_borrowed_history_json_member'),
    path('json/', show_json, name='show_json'),
    path('json_jumlah_review/', show_json_jumlah_review, name='show_json_jumlah_review'),
    path('add-review-flutter/',add_review_flutter, name='add_review_flutter'),
    path('delete-review-flutter/<int:id>/', delete_review_flutter, name='delete_review_flutter'),
]

templates/menu.html
{% load static %}
<!doctype html>

<html>
    <head>
        <head>
            <link rel="icon" href="{% static 'images/logo.png' %}">
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <script src="https://cdn.tailwindcss.com"></script>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
            <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
            <!-- Favicons -->
            <link href="/static/img/apple-touch-icon.png" rel="apple-touch-icon">
    
            <!-- Google Fonts -->
            <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    
            <!-- Vendor CSS Files -->
            <link href="/static/vendor/aos/aos.css" rel="stylesheet">
            <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
            <link href="/static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
            <link href="/static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
            <link href="/static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
            <link href="/static/vendor/remixicon/remixicon.css" rel="stylesheet">
            <link href="/static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    
            <!-- Template Main CSS File -->
            <link href="/static/css/style.css" rel="stylesheet">
    
            <!-- Vendor JS Files -->
            <script src="/static/vendor/purecounter/purecounter_vanilla.js"></script>
            <script src="/static/vendor/aos/aos.js"></script>
            <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
            <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
            <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
            <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
            <script src="/static/vendor/php-email-form/validate.js"></script>
    
            <!-- Template Main JS File -->
            <script src="/static/js/main.js"></script>
            <title>{% block title %}{% endblock %} | Read and Brew</title>
        </head>
    </head>

    <body>
        <nav class="border-b bg-[#9FA673]" >
            <div class="max-w-6xl mx-auto px-4">
                <div class="flex justify-between">
                    <div class="flex space-x-7">
                        <div>
							<!-- Website Logo -->
							<a href="/" class="flex items-center py-4 px-2">
								<img src="{% static 'images/logo.png' %}" alt="Logo" class="h-12 w-12 mr-2">
							</a>
						</div>
                        <div class="hidden md:flex items-center space-x-1">
                            {% if user.is_authenticated %}    
                                {% if user.profile.status == 'M' %}
                                    <a href="{% url 'ordernborrow:food_menu_member' %}"class="py-4 px-2 font-semibold">Food</a>
                                    <a href="{% url 'ordernborrow:drinks_menu_member' %}"class="py-4 px-2 font-semibold">Drinks</a>
                                    <a href="{% url 'ordernborrow:secret_menu_view' %}"class="py-4 px-2 font-semibold">Secret Menu</a>
                                    <a href="{% url 'ordernborrow:show_books' %}"class="py-4 px-2 font-semibold">Books</a>
                                    <a href="{% url 'ordernborrow:show_borrowed_books' %}"class="py-4 px-2 font-semibold">Borrowed</a>
                                    <a href="{% url 'ordernborrow:show_borrowed_history' %}"class="py-4 px-2 font-semibold">History</a>
                                    <a href="{% url 'ordernborrow:show_order_member' %}"class="py-4 px-2 font-semibold">Order Summary</a>
                                {% else %}
                                    <a href="{% url 'ordernborrow:supplies_and_equipment_view' %}"class="py-4 px-2 font-semibold">Supplies & Equipment</a>
                                {% endif %}
                            {% else %}
                                <a href="{% url 'ordernborrow:food_menu' %}"class="py-4 px-2 font-semibold">Food</a>
                                <a href="{% url 'ordernborrow:drinks_menu' %}"class="py-4 px-2 font-semibold">Drinks</a>
                                <a href="{% url 'ordernborrow:show_order_guest' %}"class="py-4 px-2 font-semibold">Order Summary</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="hidden md:flex items-center space-x-3 ">
                        {% if user.is_authenticated %}        
                        <a class="py-4 px-2 text-teal-500 font-semibold" style="color: #987749;">Hi, {{ user.username }}!</a>
                        <a href="{% url 'main:logout' %}" class="py-2 px-2 font-medium bg-red-500 text-white rounded-xl hover:bg-red-700">Logout</a>
                        {% else %}
                        <a href="{% url 'main:signup' %}" id="signupbutton" class="py-2 px-2 font-medium rounded-xl">Sign up</a>
                        <a href="{% url 'main:login' %}" id="loginbutton" class="py-2 px-2 font-medium rounded-xl">Log in</a>
                        {% endif %}
					</div>
                    <div class="md:hidden flex items-center">
                        {% if user.is_authenticated %}     
                        <a class="py-4 px-2 text-teal-500 font-semibold">Hi, {{ user.username }}!</a>
                        {% endif %}
						<button class="outline-none mobile-menu-button">
						<svg class=" w-6 h-6 text-gray-500 hover:text-green-500 "
							x-show="!showMenu"
							fill="none"
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							viewBox="0 0 24 24"
							stroke="currentColor">
							<path d="M4 6h16M4 12h16M4 18h16"></path>
						</svg>
					    </button>
					</div>
                </div>
            </div>
            <div class="hidden mobile-menu">
				<ul class="">
					<li><a href="{% url 'booklist:show_booklist' %}" class="block text-sm px-2 py-4 font-semibold hover:text-gray-500">Book List</a></li>
                    <hr class="hr" />
					<li>
                        {% if user.is_authenticated %}    
                            {% if user.profile.status == 'M' %}
                                <a href="{% url 'ordernborrow:food_menu_member' %}"class="block text-sm px-2 py-4 font-semibold">Food</a>
                                <a href="{% url 'ordernborrow:drinks_menu_member' %}"class="block text-sm px-2 py-4 font-semibold">Drinks</a>
                                <a href="{% url 'ordernborrow:secret_menu_view' %}"class="block text-sm px-2 py-4 font-semibold">Secret Menu</a>
                                <a href="{% url 'ordernborrow:show_books' %}"class="block text-sm px-2 py-4 font-semibold">Books</a>
                                <a href="{% url 'ordernborrow:show_borrowed_books' %}"class="block text-sm px-2 py-4 font-semibold">Borrowed</a>
                                <a href="{% url 'ordernborrow:show_borrowed_history' %}"class="block text-sm px-2 py-4 font-semibold">History</a>
                                <a href="{% url 'ordernborrow:show_order_member' %}"class="block text-sm px-2 py-4 font-semibold">Order Summary</a>
                            {% else %}
                                <a href="{% url 'ordernborrow:supplies_and_equipment_view' %}"class="block text-sm px-2 py-4 font-semibold">Supplies & Equipment</a>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'ordernborrow:food_menu' %}"class="block text-sm px-2 py-4 font-semibold">Food</a>
                            <a href="{% url 'ordernborrow:drinks_menu' %}"class="block text-sm px-2 py-4 font-semibold">Drinks</a>
                            <a href="{% url 'ordernborrow:show_order_guest' %}"class="block text-sm px-2 py-4 font-semibold">Order Summary</a>
                        {% endif %}
                    </li>
				</ul>
			</div>
            <script>
				const btn = document.querySelector("button.mobile-menu-button");
				const menu = document.querySelector(".mobile-menu");

				btn.addEventListener("click", () => {
					menu.classList.toggle("hidden");
				});
			</script>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800" style="background-color: #513C1E;">
            <div class="w-2/3 pr-10">
                <h3 id="About" class="mb-2 font-bold">About</h3>
                <p id="AboutText" class="text-sm">Read & Brew merupakan sebuah tempat yang memadukan kegemaran akan buku dengan kenyamanan sebuah kafe. Kami memiilih kafe sebagai sarana untuk meningkatkan tingkat literasi karena adanya peningkatan yang signifikan terkait dengan tingkat pengunjung kafe di kalangan anak muda. Kami memiliki harapan bahwa kafe tidak hanya bisa menjadi tempat untuk bersantai, tetapi juga menjadi sarana untuk meningkatkan literasi dari kalangan muda yang mayoritasnya masih memiliki tingkat literasi yang rendah.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-sm">About</a></li>
                    <li><a href="#" class="text-sm">Contact</a></li>
                    <li><a href="#" class="text-sm">Privacy policy</a></li>
                    <li><a href="#" class="text-sm">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

<style>
    .larger-text {
        font-size: 1.2em;
        font-weight: bolder;
    }
    .nav-links {
        display: flex;
        align-items: center;
    }

    .nav-links a {
        margin-right: 20px;
    }
    nav {
        background-color: #FDFCF8;
        border-bottom:1px solid #513C1E;
    }
    footer{
        background-color: #513C1E;
    }
    footer > div> ul > li > a {
        color: #bab28e;
    }
    footer > div> ul > li > a:hover {
        color: #868065;
    }
    #About{
        color: #bab28e;
    }
    #AboutText{
        color: #FDFCF8;
    }
    ul > li > a{
        color: #513C1E;
        }
    ul > li > a:hover{
    color: #987749;
    }
    div > a{
        color: #513C1E;
    }
    div > a:hover{
        color: #987749;
    }
    #signupbutton{
        background-color: #513C1E;
        color: #FDFCF8;
    }
    #loginbutton{
        background-color: #2B6329;
        color: #FDFCF8;
    }
    #signupbutton:hover{
        background-color: #987749;
    }
    #loginbutton:hover{
        background-color: #5b845a;
    }
    #signupbutton2{
        background-color: #513C1E;
        color: #FDFCF8;
    }
    #loginbutton2{
        background-color: #2B6329;
        color: #FDFCF8;
    }
    #signupbutton2:hover{
        background-color: #987749;
    }
    #loginbutton2:hover{
        background-color: #5b845a;
    }
</style>