booklist/urls.py
from django.urls import path
from booklist.views import get_books, show_booklist, add_book_ajax, delete_book_ajax, create_book_flutter, delete_book_flutter
app_name = 'booklist'

urlpatterns = [
    path("api/buku/", get_books, name="get_books"),
    path("", show_booklist, name="show_booklist"),
    path("add-book-ajax/", add_book_ajax, name="add_book_ajax"),
    path("delete-book-ajax/", delete_book_ajax, name="delete_book_ajax"),
    path("create-book-flutter/", create_book_flutter, name="create_book_flutter"),
    path("delete-book-flutter/", delete_book_flutter, name="delete_book_flutter"),
]

bookrequest/urls.py
from django.urls import path
from bookrequest.views import get_books, add_books, show_request, approve_request, get_books_individual, delete_request_ajax_individual, like_request_ajax, delete_request_ajax, delete_request_flutter, like_request_flutter, approve_request_flutter, create_request_flutter, get_books_individual_flutter
app_name = 'bookrequest'

urlpatterns = [
    path('get_books_individual_flutter', get_books_individual_flutter, name='get_books_individual_flutter'),
    path('create_request_flutter', create_request_flutter, name='create_request_flutter'),
    path('approve_request_flutter', approve_request_flutter, name='approve_request_flutter'),
    path('like_request_flutter', like_request_flutter, name='like_request_flutter'),
    path('delete_request_flutter', delete_request_flutter, name='delete_request_flutter'),
    path('like_request_ajax', like_request_ajax, name='like_request_ajax'),
    path('approve_request', approve_request, name='approve_request'),
    path("", show_request, name="show_request"),
    path("get_books_individual", get_books_individual, name="get_books_individual"),
    path("get_books", get_books, name="get_books"),
    path("add_books", add_books, name="add_books"),
    path('delete-request-ajax-individual/<int:id>/', delete_request_ajax_individual, name='delete_request_ajax_individual'),
    path('delete-request-ajax', delete_request_ajax, name='delete_request_ajax'),
]

main/urls.py
from django.urls import path
from main.views import *
from ordernborrow.views import *


app_name = 'main'


urlpatterns = [
    path('', show_main, name='show_main'),
    path('signup/', signup, name='signup'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'), 
]

read_and_brew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booklist/', include('booklist.urls')),
    path('ordernborrow/', include('ordernborrow.urls')),
    path('reviewmodul/', include('reviewmodul.urls')),
    path('trackernplanner/', include('trackernplanner.urls')),
    path('bookrequest/', include('bookrequest.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

booklist/models.py
from django.db import models

class Buku(models.Model):
    Gambar = models.CharField(max_length=255)
    Judul = models.CharField(max_length=255)
    Penulis = models.CharField(max_length=255)
    Kategori = models.CharField(max_length=255)
    Rating = models.IntegerField()

booklist/forms.py
from django import forms
from booklist.models import Buku

class BookForm(forms.Form):
    class meta:
        model = Buku
    judul = forms.CharField(label='Judul', max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'name':'judul', 'placeholder':'Judul Buku', 'style':"border: 1px solid #513C1E;color: #513C1E;background-color: #FDFCF8;"}))
    gambar = forms.CharField(label='Link Gambar', max_length=200 ,widget=forms.TextInput(attrs={'class': 'form-control', 'name':'gambar', 'placeholder':'Link Gambar', 'style':"border: 1px solid #513C1E;color: #513C1E;background-color: #FDFCF8;"}))
    penulis = forms.CharField(label='Penulis', max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'name':'penulis', 'placeholder':'Penulis', 'style':"border: 1px solid #513C1E;color: #513C1E;background-color: #FDFCF8;"}))
    kategori = forms.CharField(label='Kategori', max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'name':'kategori', 'list':'kategorilist', 'placeholder':'Kategori', 'style':"border: 1px solid #513C1E;color: #513C1E;background-color: #FDFCF8;"}))

booklist/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from booklist.models import Buku
from main.models import Profile
from booklist.forms import BookForm
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def show_booklist(request):
    form = BookForm(request.POST or None)
    books = Buku.objects.all()
    categories = Buku.objects.values('Kategori').distinct().values_list('Kategori', flat=True)
    if request.user.is_authenticated:
        profile  = Profile.objects.filter(user=request.user).first()
        context = {
            'books': books,
            'categories': categories,
            'profile': profile,
            'form': form,
        }
    else:
        context = {
            'books': books,
            'categories': categories,
        }
    return render(request, 'booklist.html', context)
def get_books(request):
    data = Buku.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type="application/json")

@csrf_exempt
def add_book_ajax(request):
    if request.method == 'POST':
        Judul = request.POST.get("judul")
        Gambar = request.POST.get("gambar")
        Penulis = request.POST.get("penulis")
        Kategori = request.POST.get("kategori")

        new_book = Buku(Judul=Judul, Gambar=Gambar, Penulis=Penulis, Kategori=Kategori, Rating=0)
        new_book.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_book_ajax(request):
    if request.method == "POST":
        book_id = request.POST.get("id")
        Buku.objects.filter(pk=book_id).delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_book_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        new_book = Buku.objects.create(
            Judul = data['judul'],
            Gambar = data['gambar'],
            Penulis = data['penulis'],
            Kategori = data['kategori'],
            Rating = 0
        )
        new_book.save()

        return JsonResponse({"status": "success", "messages":"Berhasil menambahkan item!"}, status=200)
    else:
        return JsonResponse({"status": "error", "messages":"Gagal menambahkan item!"}, status=401)
    
@csrf_exempt
def delete_book_flutter(request):
    if request.method == "POST":
        data = json.loads(request.body)
        Buku.objects.filter(pk=int(data['id'])).delete()
        return JsonResponse({"status": "success", "messages":"Berhasil menghapus item!"}, status=200)
    else:
        return JsonResponse({"status": "error", "messages":"Gagal menghapus item!"}, status=401)

booklist/templates/booklist.html
{% extends 'base.html' %}

{% block title %}Book List{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div id="booklistpage" class="container mx-auto">
    <h1 class="text-4xl font-semibold text-center pt-3" style="color: #513C1E;">BOOKS</h1>
    <div class="row mt-2">
        <div class="col-md-3 mt-2">
            <select style="border: 1px solid #513C1E;color: #513C1E;background-color: #FDFCF8;" class="form-select" id="categories" onchange="filterBooks()">
                <option value="">All Categories</option>
                {% for category in categories %}
                    <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-6 mt-2">
            <input style="border: 1px solid #513C1E;color: #513C1E;background-color: #FDFCF8;" type="text" class="form-control" id="search" onkeyup="filterBooks()" placeholder="Search book title..">
        </div>
        <div class="col-md-3 mt-2">
            <select style="border: 1px solid #513C1E;color: #513C1E;background-color: #FDFCF8;" class="form-select" id="sorting" onchange="sortBooks()" >
                <option value="">Sort by</option>
                <option value="rating">Rating</option>
                <option value="title">Title</option>
            </select>
        </div>
    </div>
    <div id="radiobutsort" style="display:none" class="text-center mt-3">
        <input style="color: #513C1E;" class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" value="Ascending" onchange="sortBooks()" checked>
        <label style="color: #513C1E;" class="form-check-label" for="flexRadioDefault1">
            Ascending
        </label><br>
        <input style="color: #513C1E;" class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" value="Descending" onchange="sortBooks()">
        <label style="color: #513C1E;" class="form-check-label" for="flexRadioDefault2">
            Descending
        </label>
    </div>
    {% if user.is_authenticated %}
    <div class="row mt-3">
        <div class="col text-center">
            {% if profile.status == 'E' %}
            <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Book</button>
            {% else %}
            <a href="{% url 'bookrequest:show_request' %}"><button class="btn btn-outline-primary">Request Book</button></a>
            {% endif %}
        </div>
    </div>
    {% endif %}
    <div id="item_card" class="row mt-3"></div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div style="background-color: #FDFCF8;" class="modal-content">
            <div class="modal-header">
                <h1 style="color: #513C1E;" class="modal-title fs-5" id="exampleModalLabel">Add Book</h1>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    {{ form.judul.label_tag }} {{ form.judul }}
                    {{ form.gambar.label_tag }} {{ form.gambar }}
                    {{ form.penulis.label_tag }} {{ form.penulis }}
                    {{ form.kategori.label_tag }} {{ form.kategori }}
                    <datalist id="kategorilist">
                        {% for category in categories %}
                            <option value="{{ category }}">{{ category }}</option>
                        {% endfor %}
                    </datalist>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-outline-primary" id="button_add" data-bs-dismiss="modal">Add Book</button>
            </div>
        </div>
    </div>
</div>

<style>
     .card-text{
    font-size:13px;
    }
    .checked {
    color: orange;
    }
    .card-img-top {
    width: 100%;
    height: 200px;
    object-fit: cover;
    }
    #booklistpage {
        background-color: #FDFCF8;
    }
    .card{
        background-color: #EAEFD3;
        border:1px solid #513C1E;

    }
    .list-group-item{
        background-color: #EAEFD3;
        border: solid #513C1E;
    }

</style>

<script>
function filterBooks(){
    var categories, category, books, book, i, input, filter;
    categories = document.getElementById("categories");
    category = categories.options[categories.selectedIndex].value;
    input = document.getElementById('search');
    filter = input.value.toUpperCase();
    books = document.getElementsByClassName("book");
    for (i = 0; i < books.length; i++) {
        book = books[i];
        title = book.getElementsByClassName("card-title")[0];
        txtValue = title.textContent || title.innerText;
        if (category == "" || book.getElementsByClassName("card-text")[0].textContent.indexOf(category) > -1) {
            if(txtValue.toUpperCase().indexOf(filter) > -1){
                book.style.display = "";
            } else {
                book.style.display = "none";
            }
        } else {
            book.style.display = "none";
        }
    }
}

async function displayRating() {
  const books = document.querySelectorAll(".book");
  books.forEach((book) => {
    const rating = parseInt(book.querySelector(".larger-text").textContent);
    const stars = book.querySelectorAll(".fa-star");
    for (let i = 0; i < stars.length; i++) {
      if (i < rating) {
        stars[i].classList.add("checked");
      } else {
        stars[i].classList.remove("checked");
      }
    }
  });
}


function sortBooks() {
  const sorting = document.getElementById("sorting");
  const books = document.querySelectorAll(".book");
  const sortBy = sorting.value;
  const order = document.querySelector('input[name="flexRadioDefault"]:checked').value;
  if (sortBy === "rating") {
    $("#radiobutsort").show();
    const sortedBooks = Array.from(books).sort((a, b) => {
      const ratingA = parseFloat(a.querySelector(".larger-text").textContent);
      const ratingB = parseFloat(b.querySelector(".larger-text").textContent);
      if (order === "Ascending") return ratingB - ratingA;
      else return ratingA - ratingB;
    });
    sortedBooks.forEach((book) => {
      book.parentNode.insertBefore(book, book.parentNode.firstChild);
    });
  } else if (sortBy === "title") {
    $("#radiobutsort").show();
    const sortedBooks = Array.from(books).sort((a, b) => {
      const titleA = a.querySelector(".card-title").textContent;
      const titleB = b.querySelector(".card-title").textContent;
      if (order === "Descending") return titleA.localeCompare(titleB);
      else return titleB.localeCompare(titleA);
    });
    sortedBooks.forEach((book) => {
      book.parentNode.insertBefore(book, book.parentNode.firstChild);
    });
  } else {
    $("#radiobutsort").hide();
  }
}

function addItem() {
    fetch("{% url 'booklist:add_book_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#form'))
    }).then(refreshItems).then(filterBooks).then(sortBooks)

    document.getElementById("form").reset()
    return false
}
document.getElementById("button_add").onclick = addItem

async function getItems() {
    return fetch("{% url 'booklist:get_books' %}").then((res) => res.json())
}

async function refreshItems() {
    document.getElementById("item_card").innerHTML = ""
    const items = await getItems()
    let htmlString = ``
    items.forEach((item) => {
        htmlString += `\n
        <div class="col-md-2 book">
                <div class="card mb-4">
                    <img class="card-img-top" src="${item.fields.Gambar}" alt="Book Image">
                    <div class="card-body">
                        <h5 style="color: #513C1E;" class="card-title text-center pt-2 pb-2 h6 font-weight-bold">${item.fields.Judul}</h5>
                        <hr style="color: #513C1E;" class="hr" />
                        <p style="color: #513C1E;" class="card-text pt-2"><b>Kategori: </b>${item.fields.Kategori}</p>
                        <p style="color: #513C1E;" class="card-text"><b>Penulis: </b>${item.fields.Penulis}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li hidden class="list-group-item larger-text">${item.fields.Rating}</li>
                        <li class="list-group-item text-center">
                            <div class="rating">
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                            </div>
                        </li>
                        {% if profile.status == 'E' %}
                        <li class="list-group-item text-center">
                            <button class="btn btn-outline-danger" onclick="deleteItems(${item.pk})">Delete</button>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
                        ` 
    })
    document.getElementById("item_card").innerHTML = htmlString
    displayRating()
    setMaxHeight()
}

function setMaxHeight() {
    var cards = document.getElementsByClassName("card mb-4");
    var maxHeight = 0;

    for (var i = 0; i < cards.length; i++) {
    var cardHeight = cards[i].clientHeight;
    if (cardHeight > maxHeight) {
        maxHeight = cardHeight;
    }
    }
    maxHeight += 1;
    for (var i = 0; i < cards.length; i++) {
    cards[i].style.height = maxHeight + "px";
    }
}

async function deleteItems(id) {
  let form = new FormData();
  form.append("id", id);
  await fetch("{% url 'booklist:delete_book_ajax' %}", {
    method: "POST",
    body: form,
  }).then(refreshItems).then(filterBooks).then(sortBooks)
}

refreshItems()
</script>
{% endblock %}