booklist/urls.py
from django.urls import path
from booklist.views import get_books, show_booklist, add_book_ajax, delete_book_ajax, create_book_flutter, delete_book_flutter
app_name = 'booklist'

urlpatterns = [
    path("api/buku/", get_books, name="get_books"),
    path("", show_booklist, name="show_booklist"),
    path("add-book-ajax/", add_book_ajax, name="add_book_ajax"),
    path("delete-book-ajax/", delete_book_ajax, name="delete_book_ajax"),
    path("create-book-flutter/", create_book_flutter, name="create_book_flutter"),
    path("delete-book-flutter/", delete_book_flutter, name="delete_book_flutter"),
]

main/urls.py
from django.urls import path
from main.views import *
from ordernborrow.views import *


app_name = 'main'


urlpatterns = [
    path('', show_main, name='show_main'),
    path('signup/', signup, name='signup'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'), 
]

ordernborrow/urls.py
from django.urls import path
from ordernborrow.views import *

app_name = 'ordernborrow'

urlpatterns = [
    path('guest/food/', food_view, name='food_menu'),
    path('guest/drinks/', drinks_view, name='drinks_menu'),
    path('guest/order/', order_food_ajax, name='order_food_ajax'),
    path('guest/order-summary/', show_order_guest, name="show_order_guest"),
    path('guest/get-product/', get_product_json, name='get_product_json'),
    path('guest/delete-order-ajax/<int:id>/', delete_order_ajax, name='delete_order_ajax'),
    path('guest/delete-all-order-ajax/', delete_allorder_ajax, name='delete_allorder_ajax'),
    path('guest/edit-order-ajax/<int:id>/', edit_order_ajax, name='edit_order_ajax'),

    path('member/food', food_view_member, name='food_menu_member'),
    path('member/drinks', drinks_view_member, name='drinks_menu_member'),
    path('member/order/', order_food_ajax_member, name='order_food_ajax_member'),
    path('member/secret-menu', secret_menu_view, name='secret_menu_view'),
    path('member/order-summary/', show_order_member, name="show_order_member"),
    path('member/get-product/', get_product_json_member, name='get_product_json_member'),
    path('member/delete-order-ajax/<int:id>/', delete_order_ajax_member, name='delete_order_ajax_member'),
    path('member/delete-all-order-ajax/', delete_allorder_ajax_member, name='delete_allorder_ajax_member'),
    path('member/edit-order-ajax/<int:id>/', edit_order_ajax_member, name='edit_order_ajax_member'),

    path('member/borrow/', show_books, name='show_books'),
    path('member/show-borrowed/', show_borrowed_books, name='show_borrowed_books'),
    path('member/borrow-book/', borrow_book_member, name='borrow_book_member'),
    path('member/return-book/<int:id>/', return_book_member, name='return_book_member'),
    path('member/borrowed/', show_json_borrowedbooks, name='show_json_borrowedbooks'),
    path('member/borrowed-history/', show_json_borrowedhistory, name='show_json_borrowedhistory'),
    path('member/show-borrowed-history/', show_borrowed_history, name='show_borrowed_history'),
    path('member/create-borrowed-history/', create_borrowed_history, name='create_borrowed_history'),

    path('employee/supplies-equipment/', supplies_and_equipment_view, name='supplies_and_equipment_view'),

    path('api/get-food/', get_food, name="get_food"),
    path('api/get-drink/', get_drink, name="get_drink"),
    path('guest/order-drink-flutter/', create_order_flutter, name="order_drink"),
    path('guest/order-food-flutter/', create_order_flutter, name="order_food"),
    path('guest/delete-all-order-flutter/', delete_allorder_flutter, name='delete_allorder_flutter'),
    path('guest/edit-order-flutter/<int:id>/', edit_order_flutter, name='edit_order_flutter'),
    path('guest/delete-order-flutter/<int:id>/', delete_order_flutter, name='delete_order_flutter'),

    path('member/order-drink-flutter/', create_order_member_flutter, name="order_drink_member"),
    path('member/order-food-flutter/', create_order_member_flutter, name="order_food_member"),
    path('member/get-product-flutter/', get_product_flutter_member, name="get_product_flutter_member"),
    path('member/delete-all-order-flutter/', delete_allorder_member_flutter, name="delete_allorder_member_flutter"),
    path('member/edit-order-flutter/<int:id>/', edit_order_member_flutter, name="edit_order_member_flutter"),
    path('member/delete-order-flutter/<int:id>/', delete_order_member_flutter, name="delete_order_member_flutter"),

    path('member/borrow-book-flutter/', borrow_book_flutter, name='borrow_book_flutter'),
    path('member/return-book-flutter/', return_book_flutter, name='return_book_flutter'),
]

read_and_brew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booklist/', include('booklist.urls')),
    path('ordernborrow/', include('ordernborrow.urls')),
    path('reviewmodul/', include('reviewmodul.urls')),
    path('trackernplanner/', include('trackernplanner.urls')),
    path('bookrequest/', include('bookrequest.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

ordernborrow/models.py
from django.db import models
from booklist.models import Buku
from django.contrib.auth.models import User

# Order model for Guest
class Order(models.Model):
    food_name = models.CharField(max_length=255)
    food_price = models.DecimalField(max_digits=6, decimal_places=2)
    amount = models.PositiveIntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add=True)

# Order model for Member
class OrderMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food_name = models.CharField(max_length=255)
    food_price = models.DecimalField(max_digits=6, decimal_places=2)
    amount = models.PositiveIntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add=True)

# Borrowed Book model for Member
class BorrowedBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Buku, on_delete=models.CASCADE)
    borrowed = models.BooleanField(default=True)

# Borrowed History model for Member
class BorrowedHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Buku, on_delete=models.CASCADE)

class Food(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=255)

class Drink(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=255)

ordernborrow/forms.py
from django.forms import ModelForm
from ordernborrow.models import *
from django import forms

class OrderForm(forms.Form):
    class Meta:
        model = Order
    amount = forms.IntegerField(label="Amount", widget=forms.TextInput(attrs={"class":"form-control","id":"amount", "name":"amount", "min":"1", "type":"number"}))

class OrderMemberForm(ModelForm):
    class Meta:
        model = OrderMember
        fields = ["food_name", "food_price", "amount"]


class BorrowBookForm(ModelForm):
    class Meta:
        model = BorrowedBook
        fields = ["user", "book", "borrowed"]

ordernborrow/views.py
#pylint: disable=E1101
import json
from django.shortcuts import render
from ordernborrow.models import *
from booklist.models import Buku
from ordernborrow.forms import *
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

# For Guest (no login)
def food_view(request):
    form = OrderForm(request.POST or None)
    content = {
        "forms": form,
        "food":{
            "Bagel with Cream Cheese": {
                "price": 2.99,
                "description": "A freshly baked bagel served with a generous portion of cream cheese.",
                "ordered": Order.objects.filter(food_name="Bagel with Cream Cheese").exists()
            },
            "Egg and Cheese Sandwich": {
                "price": 4.49,
                "description": "A breakfast classic - scrambled eggs and melted cheese on a toasted bun.",
                "ordered": Order.objects.filter(food_name="Egg and Cheese Sandwich").exists()
            },
            "Cinnamon Roll": {
                "price": 3.49,
                "description": "A sweet and gooey cinnamon roll with icing on top.",
                "ordered": Order.objects.filter(food_name="Cinnamon Roll").exists()

            },
            "Chocolate Croissant": {
                "price": 2.99,
                "description": "A buttery and flaky croissant mixed with chocolate, perfect with your coffee.",
                "ordered": Order.objects.filter(food_name="Croissant").exists()

            },
            "New York Style Pizza": {
                "price": 9.99,
                "description": "A classic thin-crust pizza with your choice of toppings, just like in the Big Apple.",
                "ordered": Order.objects.filter(food_name="New York Style Pizza").exists()
            },
            "Chicago Deep Dish Pizza": {
                "price": 12.99,
                "description": "A thick and cheesy deep-dish pizza, a Windy City specialty.",
                "ordered": Order.objects.filter(food_name="Chicago Deep Dish Pizza").exists()
            },
            "Caprese Panini": {
                "price": 7.99,
                "description": "Fresh mozzarella, ripe tomatoes, and basil pesto on grilled ciabatta bread.",
                "ordered": Order.objects.filter(food_name="Caprese Panini").exists()

            },
            "Chicken Quesadilla": {
                "price": 8.49,
                "description": "Sliced chicken, cheese, and vegetables folded in a tortilla and grilled.",
                "ordered": Order.objects.filter(food_name="Chicken Quesadilla").exists()
            },
            "Spinach and Feta Quiche": {
                "price": 6.99,
                "description": "A savory pastry filled with spinach, feta cheese, and eggs.",
                "ordered": Order.objects.filter(food_name="Spinach and Feta Quiche").exists()
            },
            "Avocado Toast": {
                "price": 5.99,
                "description": "Sliced avocado on toasted artisan bread, topped with seasoning.",
                "ordered": Order.objects.filter(food_name="Avocado Toast").exists()
            },
            "Muffin": {
                "price": 2.49,
                "description": "A freshly baked muffin in your choice of flavor.",
                "ordered": Order.objects.filter(food_name="Muffin").exists()
            },
            "Blueberry Scone": {
                "price": 2.79,
                "description": "A tender and crumbly scone filled with juicy blueberries.",
                "ordered": Order.objects.filter(food_name="Blueberry Scone").exists()

            },
            "Breakfast Burrito": {
                "price": 6.49,
                "description": "A hearty breakfast burrito filled with eggs, sausage, cheese, and vegetables.",
                "ordered": Order.objects.filter(food_name="Breakfast Burrito").exists()
            },
            "Fruit Parfait": {
                "price": 4.99,
                "description": "A delicious parfait made with yogurt, granola, and a mix of fresh fruits.",
                "ordered": Order.objects.filter(food_name="Fruit Parfait").exists()
            },
            "Quiche Lorraine": {
                "price": 6.99,
                "description": "A classic quiche filled with bacon, Swiss cheese, and a savory custard.",
                "ordered": Order.objects.filter(food_name="Quiche Lorraine").exists()
            }
        }
    }

    return render(request, 'foodmenu.html', content)

# For Member (login)
def food_view_member(request):
    content = {
        "food":{
            "Bagel with Cream Cheese": {
                "price": 2.99,
                "description": "A freshly baked bagel served with a generous portion of cream cheese.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Bagel with Cream Cheese").exists()
            },
            "Egg and Cheese Sandwich": {
                "price": 4.49,
                "description": "A breakfast classic - scrambled eggs and melted cheese on a toasted bun.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Egg and Cheese Sandwich").exists()
            },
            "Cinnamon Roll": {
                "price": 3.49,
                "description": "A sweet and gooey cinnamon roll with icing on top.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Cinnamon Roll").exists()

            },
            "Chocolate Croissant": {
                "price": 2.99,
                "description": "A buttery and flaky croissant mixed with chocolate, perfect with your coffee.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Croissant").exists()

            },
            "New York Style Pizza": {
                "price": 9.99,
                "description": "A classic thin-crust pizza with your choice of toppings, just like in the Big Apple.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="New York Style Pizza").exists()
            },
            "Chicago Deep Dish Pizza": {
                "price": 12.99,
                "description": "A thick and cheesy deep-dish pizza, a Windy City specialty.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Chicago Deep Dish Pizza").exists()
            },
            "Caprese Panini": {
                "price": 7.99,
                "description": "Fresh mozzarella, ripe tomatoes, and basil pesto on grilled ciabatta bread.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Caprese Panini").exists()

            },
            "Chicken Quesadilla": {
                "price": 8.49,
                "description": "Sliced chicken, cheese, and vegetables folded in a tortilla and grilled.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Chicken Quesadilla").exists()
            },
            "Spinach and Feta Quiche": {
                "price": 6.99,
                "description": "A savory pastry filled with spinach, feta cheese, and eggs.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Spinach and Feta Quiche").exists()
            },
            "Avocado Toast": {
                "price": 5.99,
                "description": "Sliced avocado on toasted artisan bread, topped with seasoning.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Avocado Toast").exists()
            },
            "Muffin": {
                "price": 2.49,
                "description": "A freshly baked muffin in your choice of flavor.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Muffin").exists()
            },
            "Blueberry Scone": {
                "price": 2.79,
                "description": "A tender and crumbly scone filled with juicy blueberries.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Blueberry Scone").exists()

            },
            "Breakfast Burrito": {
                "price": 6.49,
                "description": "A hearty breakfast burrito filled with eggs, sausage, cheese, and vegetables.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Breakfast Burrito").exists()
            },
            "Fruit Parfait": {
                "price": 4.99,
                "description": "A delicious parfait made with yogurt, granola, and a mix of fresh fruits.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Fruit Parfait").exists()
            },
            "Quiche Lorraine": {
                "price": 6.99,
                "description": "A classic quiche filled with bacon, Swiss cheese, and a savory custard.",
                "ordered": OrderMember.objects.filter(user = request.user).filter(food_name="Quiche Lorraine").exists()
            }
        }
    }

    return render(request, 'foodmenumember.html', content)

# For Guest (no login)
def drinks_view(request):
    content = {
        "drinks": {
            "Latte": {
                "price": 3.99,
                "description": "Espresso with creamy steamed milk and a hint of vanilla.",
                "ordered": Order.objects.filter(food_name="Latte").exists()
            },
            "Cappuccino": {
                "price": 4.49,
                "description": "Espresso topped with frothy milk and a sprinkle of cocoa.",
                "ordered": Order.objects.filter(food_name="Cappuccino").exists()
            },

ordernborrow/templates/drinkmenu.html
{% extends "menu.html" %}
{% block title %}Order & Borrow{% endblock %}
{% block content %}
<!-- Order form modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Order</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: black;" onclick="clearOrderForm()">&#x2715</button>
            </div>
            <div class="modal-body">
                <form id="orderform">
                    {% csrf_token %}
                    <input type="hidden" id="food_name" name="food_name">
                    <input type="hidden" id="food_price" name="food_price">
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount" min="1">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" style="background-color: #dc3545; color: #fff;" data-bs-dismiss="modal" onclick="clearOrderForm()">Close</button>
                <button type="button" class="btn btn-success" style="background-color:#3A833A; color: #fff;" data-bs-dismiss="modal" onclick="placeOrder()">Place Order</button>

            </div>
        </div>
    </div>
</div>

<!-- Alert modal -->
<div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="alertModalLabel">Alert</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: black;">&#x2715</button>
            </div>
            <div class="modal-body">
                <p id="alertMessage">This is the alert message.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" style="background-color:#20809d; color: white;">OK</button>
            </div>
        </div>
    </div>
</div>

<!-- Display drink menu in cards -->
<div class="container mx-auto">
    <h1 class="text-4xl font-semibold mb-6 text-center">Drinks</h1>
    <div class="row">
        {% for item, details in drinks.items %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title h4 font-weight-bold">{{ item }}</h5>
                        <p class="card-text italic">{{ details.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item larger-text">Price: ${{ details.price }}</li>
                    </ul>
                    <button class="btn btn-success order-food" data-food-name="{{ item }}" data-food-price="{{ details.price }}" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="fillOrderFields(this)" {% if details.ordered %}disabled{% endif %}>
                        {% if details.ordered %}Ordered{% else %}Order{% endif %}
                    </button>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<script>
    
    // Function to display an alert modal and change its message.
    async function showAlert(message) {
        $("#alertMessage").text(message);
        $('#alertModal').modal('show');
    }
    
   // Function to autofill the drink name and price
    async function fillOrderFields(button) {
        var foodName = $(button).data('food-name');
        var foodPrice = $(button).data('food-price');
        $('#food_name').val(foodName);
        $('#food_price').val(foodPrice);
    }

    //Function to place order
    async function placeOrder() {
        var amount = $('#amount').val();
        var foodName = $('#food_name').val();
        var foodPrice = $('#food_price').val();

        $.ajax({
            type: "POST",
            url: "{% url 'ordernborrow:order_food_ajax' %}",
            data: {
                food_name: foodName,
                food_price: foodPrice,
                amount: amount,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function(data) {
                $('.order-food[data-food-name="' + foodName + '"]').text('Ordered').prop('disabled', true);
                showAlert("Order placed successfully! Please check your orders in Order Summary!");
            },
            error: function(error) {
                showAlert("Error placing order.");
            }
        });
        document.getElementById("orderform").reset()
    }

    function clearOrderForm() {
        document.getElementById('orderform').reset();
    }
</script>
{% endblock %}

ordernborrow/templates/returnbook.html
{% extends 'menu.html' %}
{% block title %}Order & Borrow{% endblock %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Alert modal -->
<div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="alertModalLabel">Alert</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: black;">&#x2715</button>
            </div>
            <div class="modal-body">
                <p id="alertMessage">This is the alert message.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" style="background-color:#20809d; color: white;">OK</button>
            </div>
        </div>
    </div>
</div>

<!-- Return confirmation modal -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="confirmationModalLabel">Order & Borrow</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: black;">&#x2715</button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to return this book?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="background-color: #6c757d; color: #fff;">Cancel</button>
                <button type="button" class="btn btn-success" id="confirmBorrow" data-bs-dismiss="modal" style="background-color: #dc3545; color: #fff;" onclick="returnBook()">Return</button>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="book" name="book">
<div class="row row-cols-1 row-cols-md-3 row-cols-sm-2 row-cols-xs-1 g-4">
    <!-- Display books borrowed by user in cards -->
</div>

<style>
    .card-text{
   font-size:13px;
   }
   .checked {
   color: orange;
   }
   .card-img-top {
   width: 100%;
   height: 200px;
   object-fit: cover;
   }
   #booklistpage {
       background-color: #FDFCF8;
   }
   .card{
       background-color: #EAEFD3;
       border:1px solid #513C1E;

   }
   .list-group-item{
       background-color: #EAEFD3;
       border: solid #513C1E;
   }

</style>

<script>
    
    // Function to get all books from the dataset
    async function getBooks() {
        return fetch("{% url 'booklist:get_books' %}").then((res) => res.json())
    }

    // Function to get all books that has been borrowed
    async function getBorrowedBooks(){
        return fetch("{% url 'ordernborrow:show_json_borrowedbooks' %}").then((res) => res.json())
    }

    // Function to display an alert modal and change its message.
    async function showAlert(message) {
        $("#alertMessage").text(message);
        $('#alertModal').modal('show');
    }

    // Function to display books borrowed by user in cards
    async function refreshBooks() {
        document.querySelector(".row").innerHTML = "";
        const books = await getBooks();
        const borrowedBooks = await getBorrowedBooks();
        const currentUserId = "{{ current_user_id }}";

        const userBorrowedBooks = books.filter((item, index) => {
            const bookId = item.pk;
            return borrowedBooks.some(book => book.fields.book == bookId && book.fields.user == currentUserId);
        });

        if (userBorrowedBooks.length === 0) {
            const noBooksMessage = `
                <div class="col-md-12 text-center">
                    <p>You haven't borrowed any books yet.</p>
                </div>`;
            const row = document.querySelector(".row");
            row.innerHTML += noBooksMessage;
        }
        else{
            books.forEach((item, index) => {
                const bookId = item.pk;
                const isBorrowed = borrowedBooks.some(book => book.fields.book == bookId && book.fields.user == currentUserId);

                if (isBorrowed) {
                    const bookCard = `
                    <div class="col-md-2 book">
                        <div class="card mb-4">
                            <img class="card-img-top" src="${item.fields.Gambar}" alt="Book Image">
                            <div class="card-body">
                                <h5 style="color: #513C1E;" class="card-title text-center pt-2 pb-2 h6 font-weight-bold">${item.fields.Judul}</h5>
                                <hr style="color: #513C1E;" class="hr" />
                                <p style="color: #513C1E;" class="card-text pt-2"><b>Kategori: </b>${item.fields.Kategori}</p>
                                <p style="color: #513C1E;" class="card-text"><b>Penulis: </b>${item.fields.Penulis}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li hidden class="list-group-item larger-text">${item.fields.Rating}</li>
                                <li class="list-group-item text-center">
                                    <div class="rating">
                                        <span class="fa fa-star"></span>
                                        <span class="fa fa-star"></span>
                                        <span class="fa fa-star"></span>
                                        <span class="fa fa-star"></span>
                                        <span class="fa fa-star"></span>
                                    </div>
                                </li>
                                <li class="btn btn-danger" onclick="showConfirmationModal(this)" data-book="${bookId}">
                                    Return
                                </li>
                            </ul>
                        </div>
                    </div>`;

                    const row = document.querySelector(".row");
                    row.innerHTML += bookCard;
                }
            });
        }
        setMaxHeight()
        displayRating()
    }

    // Function to show return confirmation modal
    async function showConfirmationModal(button) {   
        var book = $(button).data('book');   
        $('#book').val(book);
        const confirmationModal = new bootstrap.Modal(document.getElementById('confirmationModal'));
        confirmationModal.show();
    }

    // Function to return borrowed books by user
    async function returnBook() {
        var book = $('#book').val();
        fetch(`{% url 'ordernborrow:return_book_member' 0 %}`.replace('0', book), {
            method: "POST"
        })
        .then((response) => {
            if (response.ok) {
                refreshBooks()
                showAlert("Successfully returned! Thank you for returning the book!")
                makeBorrowHistory()
            } else {
                showAlert("Return failed. Please try again.");
            }
        })
        .catch((error) => {
            console.error("Error while returning book:", error);
            showAlert("Return failed. Please try again.");
        });
    }

      // Function to put book that has been returned in borrowed history
      async function makeBorrowHistory() {
        var book = $('#book').val();

        $.ajax({
            type: "POST",
            url: "{% url 'ordernborrow:create_borrowed_history' %}",
            data: {
                book: book,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function(data) {
            },
            error: function(error) {
            }
        });
    }

    async function displayRating() {
        const books = document.querySelectorAll(".book");
        books.forEach((book) => {
            const rating = parseInt(book.querySelector(".larger-text").textContent);
            const stars = book.querySelectorAll(".fa-star");
            for (let i = 0; i < stars.length; i++) {
            if (i < rating) {
                stars[i].classList.add("checked");
            } else {
                stars[i].classList.remove("checked");
            }
            }
        });
    }

    function setMaxHeight() {
        var cards = document.getElementsByClassName("card mb-4");
        var maxHeight = 0;

        for (var i = 0; i < cards.length; i++) {
        var cardHeight = cards[i].clientHeight;
        if (cardHeight > maxHeight) {
            maxHeight = cardHeight;
        }
        }
        maxHeight += 1;
        for (var i = 0; i < cards.length; i++) {
        cards[i].style.height = maxHeight + "px";
        }
    }
    refreshBooks()

</script>
{% endblock %}