booklist/urls.py
from django.urls import path
from booklist.views import get_books, show_booklist, add_book_ajax, delete_book_ajax, create_book_flutter, delete_book_flutter
app_name = 'booklist'

urlpatterns = [
    path("api/buku/", get_books, name="get_books"),
    path("", show_booklist, name="show_booklist"),
    path("add-book-ajax/", add_book_ajax, name="add_book_ajax"),
    path("delete-book-ajax/", delete_book_ajax, name="delete_book_ajax"),
    path("create-book-flutter/", create_book_flutter, name="create_book_flutter"),
    path("delete-book-flutter/", delete_book_flutter, name="delete_book_flutter"),
]

bookrequest/urls.py
from django.urls import path
from bookrequest.views import get_books, add_books, show_request, approve_request, get_books_individual, delete_request_ajax_individual, like_request_ajax, delete_request_ajax, delete_request_flutter, like_request_flutter, approve_request_flutter, create_request_flutter, get_books_individual_flutter
app_name = 'bookrequest'

urlpatterns = [
    path('get_books_individual_flutter', get_books_individual_flutter, name='get_books_individual_flutter'),
    path('create_request_flutter', create_request_flutter, name='create_request_flutter'),
    path('approve_request_flutter', approve_request_flutter, name='approve_request_flutter'),
    path('like_request_flutter', like_request_flutter, name='like_request_flutter'),
    path('delete_request_flutter', delete_request_flutter, name='delete_request_flutter'),
    path('like_request_ajax', like_request_ajax, name='like_request_ajax'),
    path('approve_request', approve_request, name='approve_request'),
    path("", show_request, name="show_request"),
    path("get_books_individual", get_books_individual, name="get_books_individual"),
    path("get_books", get_books, name="get_books"),
    path("add_books", add_books, name="add_books"),
    path('delete-request-ajax-individual/<int:id>/', delete_request_ajax_individual, name='delete_request_ajax_individual'),
    path('delete-request-ajax', delete_request_ajax, name='delete_request_ajax'),
]

main/urls.py
from django.urls import path
from main.views import *
from ordernborrow.views import *


app_name = 'main'


urlpatterns = [
    path('', show_main, name='show_main'),
    path('signup/', signup, name='signup'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'), 
]

ordernborrow/urls.py
from django.urls import path
from ordernborrow.views import *

app_name = 'ordernborrow'

urlpatterns = [
    path('guest/food/', food_view, name='food_menu'),
    path('guest/drinks/', drinks_view, name='drinks_menu'),
    path('guest/order/', order_food_ajax, name='order_food_ajax'),
    path('guest/order-summary/', show_order_guest, name="show_order_guest"),
    path('guest/get-product/', get_product_json, name='get_product_json'),
    path('guest/delete-order-ajax/<int:id>/', delete_order_ajax, name='delete_order_ajax'),
    path('guest/delete-all-order-ajax/', delete_allorder_ajax, name='delete_allorder_ajax'),
    path('guest/edit-order-ajax/<int:id>/', edit_order_ajax, name='edit_order_ajax'),

    path('member/food', food_view_member, name='food_menu_member'),
    path('member/drinks', drinks_view_member, name='drinks_menu_member'),
    path('member/order/', order_food_ajax_member, name='order_food_ajax_member'),
    path('member/secret-menu', secret_menu_view, name='secret_menu_view'),
    path('member/order-summary/', show_order_member, name="show_order_member"),
    path('member/get-product/', get_product_json_member, name='get_product_json_member'),
    path('member/delete-order-ajax/<int:id>/', delete_order_ajax_member, name='delete_order_ajax_member'),
    path('member/delete-all-order-ajax/', delete_allorder_ajax_member, name='delete_allorder_ajax_member'),
    path('member/edit-order-ajax/<int:id>/', edit_order_ajax_member, name='edit_order_ajax_member'),

    path('member/borrow/', show_books, name='show_books'),
    path('member/show-borrowed/', show_borrowed_books, name='show_borrowed_books'),
    path('member/borrow-book/', borrow_book_member, name='borrow_book_member'),
    path('member/return-book/<int:id>/', return_book_member, name='return_book_member'),
    path('member/borrowed/', show_json_borrowedbooks, name='show_json_borrowedbooks'),
    path('member/borrowed-history/', show_json_borrowedhistory, name='show_json_borrowedhistory'),
    path('member/show-borrowed-history/', show_borrowed_history, name='show_borrowed_history'),
    path('member/create-borrowed-history/', create_borrowed_history, name='create_borrowed_history'),

    path('employee/supplies-equipment/', supplies_and_equipment_view, name='supplies_and_equipment_view'),

    path('api/get-food/', get_food, name="get_food"),
    path('api/get-drink/', get_drink, name="get_drink"),
    path('guest/order-drink-flutter/', create_order_flutter, name="order_drink"),
    path('guest/order-food-flutter/', create_order_flutter, name="order_food"),
    path('guest/delete-all-order-flutter/', delete_allorder_flutter, name='delete_allorder_flutter'),
    path('guest/edit-order-flutter/<int:id>/', edit_order_flutter, name='edit_order_flutter'),
    path('guest/delete-order-flutter/<int:id>/', delete_order_flutter, name='delete_order_flutter'),

    path('member/order-drink-flutter/', create_order_member_flutter, name="order_drink_member"),
    path('member/order-food-flutter/', create_order_member_flutter, name="order_food_member"),
    path('member/get-product-flutter/', get_product_flutter_member, name="get_product_flutter_member"),
    path('member/delete-all-order-flutter/', delete_allorder_member_flutter, name="delete_allorder_member_flutter"),
    path('member/edit-order-flutter/<int:id>/', edit_order_member_flutter, name="edit_order_member_flutter"),
    path('member/delete-order-flutter/<int:id>/', delete_order_member_flutter, name="delete_order_member_flutter"),

    path('member/borrow-book-flutter/', borrow_book_flutter, name='borrow_book_flutter'),
    path('member/return-book-flutter/', return_book_flutter, name='return_book_flutter'),
]

read_and_brew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booklist/', include('booklist.urls')),
    path('ordernborrow/', include('ordernborrow.urls')),
    path('reviewmodul/', include('reviewmodul.urls')),
    path('trackernplanner/', include('trackernplanner.urls')),
    path('bookrequest/', include('bookrequest.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

reviewmodul/urls.py
from django.urls import path
from reviewmodul.views import *

app_name = 'reviewmodul'

urlpatterns = [
    path('show_review/', show_review, name='show_review'),
    path('add_review_ajax/', add_review_ajax, name='add_review_ajax'),
    path('get-review/', get_review_json, name='get_review_json'),
    path('get-review-member/', get_review_json_member, name='get_review_json_member'),
    path('show_review/delete_review/<int:id>/', delete_review, name='delete_review'),
    path('get_borrowed_history_json_member', get_borrowed_history_json_member, name='get_borrowed_history_json_member'),
    path('json/', show_json, name='show_json'),
    path('json_jumlah_review/', show_json_jumlah_review, name='show_json_jumlah_review'),
    path('add-review-flutter/',add_review_flutter, name='add_review_flutter'),
    path('delete-review-flutter/<int:id>/', delete_review_flutter, name='delete_review_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=1)
    full_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=200)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from main.models import *

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
        'style': 'background-color: #FDFCF8;'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
        'style': 'background-color: #FDFCF8;'
    }))

class SignUpForm(UserCreationForm):
    STATUS_CHOICES = [('M', 'Member'), ('E', 'Employee')]
    status = forms.ChoiceField(
        required=True,
        choices=STATUS_CHOICES,
        widget=forms.Select(attrs={
            'style': 'background-color: #FDFCF8;'
        })
    )
    full_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
        'style': 'background-color: #FDFCF8;'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
        'style': 'background-color: #FDFCF8;'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl',
        'style': 'background-color: #FDFCF8;'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
        'style': 'background-color: #FDFCF8;'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl',
        'style': 'background-color: #FDFCF8;'
    }))
    class Meta:
        model = User
        fields = ('status', 'full_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.status = self.cleaned_data["status"]
        user.full_name = self.cleaned_data["full_name"]
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()
        
        return user

main/views.py
from main.models import Profile
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect
from main.forms import SignUpForm, LoginForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers


def show_main(request):
    return render(request, "main.html")

def login_user(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("main:show_main")) # membuat response
            return response
        else:
            messages.info(request, 'Invalid username/password!')
            
    context = {'form':form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = redirect('main:show_main')
    return response

def signup(request):
    form = SignUpForm()

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            Profile.objects.create(
                user = new_user,
                status = new_user.status,
                full_name = new_user.full_name,
                email = new_user.email
                )
            messages.success(request, 'Sign up successful!')
            return redirect('main:login')
    
    context = {'form':form}
    return render(request, 'signup.html', context)

main/templates/login.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<section id="login">
    <div class="w-5/6 my-6 mx-auto p-6 rounded-xl" style="background-color: #EAEFD3;">
        <h1 class="mb-6 text-3xl">Log in</h1>
    
        <form method="post" action=".">
            {% csrf_token %}
    
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
    
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>
    
            {% if messages %}
                <div class="alert alert-danger">
                    <ul>
                        {% for message in messages %}
                            <li class="text-lg text-red-500">{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
    
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
    
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <a class="text-lg">Don't have an account yet?</a>
            <a class="underline text-lg text-blue-700" href="{% url 'main:signup' %}">Sign up</a>
            <br>
    
            <button id="submitbutton" class="my-2 py-4 px-8 text-lg rounded-xl">Submit</button>
        </form>
    </div>
</section>

<style>
    #login {
        background-color: #FDFCF8;
    }
    #submitbutton {
        background-color: #2B6329;
        color: #FDFCF8;
    }
    #submitbutton:hover {
        background-color: #448941;
    }
</style>
{% endblock %}

main/templates/main.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
    <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
        <h1>Read and Brew</h1>
        <h2>Library Cafe</h2>
        </div>
    </div>
    <div class="text-center">
        <a href="
        {% if user.is_authenticated %}   
            {% if user.profile.status == 'M' %}
                {% url 'ordernborrow:food_menu_member' %}
            {% else %}
                {% url 'ordernborrow:supplies_and_equipment_view' %}
            {% endif %}
        {% else %}
            {% url 'ordernborrow:food_menu' %}
        {% endif %}
        " class="btn-get-started scrollto">Order</a>
    </div>

    <div class="row icon-boxes">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
        <div class="icon-box">
            <div class="icon"><i class="ri-book-line"></i></div>
            <h4 class="title"><a href="{% url 'booklist:show_booklist' %}">Book List</a></h4>
            <p class="description">Kumpulan buku-buku dengan berbagai kategori</p>
        </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
        <div class="icon-box">
            <div class="icon"><i class="ri-inbox-unarchive-line"></i></div>
            <h4 class="title"><a href="{% url 'trackernplanner:show_tracker_planner' %}">Book Tracker</a></h4>
            <p class="description">Melacak buku yang sedang dibaca</p>
        </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
        <div class="icon-box">
            <div class="icon"><i class="ri-quill-pen-line"></i></div>
            <h4 class="title"><a href="{% url 'reviewmodul:show_review' %}">Review Forum</a></h4>
            <p class="description">Review dan komentar pada buku dan cafe</p>
        </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="500">
        <div class="icon-box">
            <div class="icon"><i class="ri-file-add-line"></i></div>
            <h4 class="title"><a href="{% url 'bookrequest:show_request' %}">Book Request</a></h4>
            <p class="description">Ajukan buku untuk ditambahkan pada cafe</p>
        </div>
        </div>

    </div>
    </div>
</section><!-- End Hero -->
{% endblock %}

main/templates/showorderguest.html
{% extends 'menu.html' %}
{% block title %}Order & Borrow{% endblock %}

{% block content %}
<!-- delete confirmation modal -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="confirmationModalLabel">Confirm Deletion</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this order?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="background-color: #6c757d; color: #fff;">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDelete" data-bs-dismiss="modal" style="background-color: #dc3545; color: #fff;">Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- edit order modal -->
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="editModalLabel">Edit Order</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: black;">&#x2715</button>
            </div>
            <div class="modal-body">
                <form id="editOrderForm">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="editAmount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="editAmount" name="amount" min="1">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" style="background-color: #dc3545; color: #fff;" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success" style="background-color:#3A833A; color: #fff;" data-bs-dismiss="modal" id="confirmChanges">Save Changes</button>
            </div>
        </div>
    </div>
</div>

<!-- alert modal -->
<div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="alertModalLabel">Alert</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: black;">&#x2715</button>
            </div>
            <div class="modal-body">
                <p id="alertMessage">This is the alert message.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" style="background-color:#20809d; color: white;">OK</button>
            </div>
        </div>
    </div>
</div>

<!-- payment modal -->
<div class="modal fade" id="paymentModal" tabindex="-1" aria-labelledby="paymentModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="paymentModalLabel">Payment Details</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- TODO tambahin sesuatu -->
                <p>Total Amount: <span id="totalAmount"></span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="background-color: #6c757d; color: #fff;">Cancel</button>
                <button type="button" class="btn btn-success" data-bs-dismiss="modal" id="confirmPayment" style="background-color:#3A833A; color: #fff;">Pay Now</button>
            </div>
        </div>
    </div>
</div>

<div class="container text-center">
    <div id="orders-container">
        <!-- Orders di tabel sini-->
    </div>
    
    <button class="btn btn-success" id="checkoutButton" onclick="showPaymentModal()">Checkout</button>
</div>
    
<style>
    table {
        border-collapse: collapse;
        width: 80%; 
        margin: 0 auto; 
    }
    
    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    th {
        background-color: #f2f2f2; 
    }

    tr:nth-child(odd) {
        background-color: white;
    }

    #checkoutButton {
        margin-top: 30px;
        font-weight: bold;
        padding: 15px 20px; 
    }
</style>

<script>
     $(document).ready(function() {
        loadOrders();
    });
    
    // fungsi untuk ubah message alert modal
    async function showAlert(message) {
        $("#alertMessage").text(message);
        $('#alertModal').modal('show');
    }

    // buat & refresh order tabel
   async function loadOrders() {
        $.get("{% url 'main:get_product_json' %}", function(data) {
            var orders = JSON.parse(data);
            var ordersContainer = $('#orders-container');
            var checkoutButton = $('#checkoutButton');
    
            if (orders.length === 0) {
                ordersContainer.html("<p>No orders available.</p>");
                checkoutButton.hide(); 
            } else {
                checkoutButton.show(); 
                var table = '<table>';
                table += '<tr><th style="text-align: center; vertical-align: middle;">No.</th><th style="text-align: center; vertical-align: middle;">Food Name</th><th style="text-align: center; vertical-align: middle;">Food Price</th><th style="text-align: center; vertical-align: middle;">Amount</th><th style="text-align: center; vertical-align: middle;">Edit</th><th style="text-align: center; vertical-align: middle;">Delete</th><th style="text-align: center; vertical-align: middle;">Total Price</th></tr>';
                var totalPrice = 0; 
                
                for (var i = 0; i < orders.length; i++) {
                    var order = orders[i];
                    var foodPrice = parseFloat(order.fields.food_price);
                    var amount = parseFloat(order.fields.amount);
                    var totalRowPrice = foodPrice * amount; 
                    totalPrice += totalRowPrice; 
                    table += '<tr>';
                    table += '<td style="text-align: center; vertical-align: middle;">' + (i+1) + '</td>';
                    table += '<td>' + order.fields.food_name + '</td>';
                    table += '<td style="text-align: center; vertical-align: middle;">$' + foodPrice + '</td>';
                    table += '<td style="text-align: center; vertical-align: middle;">' + amount + '</td>';
                    table += '<td style="text-align: center; vertical-align: middle;"><button class="btn btn-primary" onclick="showEditModal('+ order.pk +')">Edit</button></td>';
                    table += '<td style="text-align: center; vertical-align: middle;"><button class="btn btn-danger" onclick="showConfirmationModal('+ order.pk +')">Delete</button></td>';
                    table += '<td style="text-align: center; vertical-align: middle;">$' + totalRowPrice.toFixed(2) + '</td>';
                    table += '</tr>';
                }
                
                table += '<tr>';
                table += '<td colspan="6" style="text-align: center; vertical-align: middle;"><strong>Final Price:</strong></td>';
                table += '<td style="text-align: center; vertical-align: middle;"><strong>$' + totalPrice.toFixed(2) + '</strong></td>';
                table += '</tr>';
                
                table += '</table>';
                ordersContainer.html(table);
            }
        });
    }
    
    // Function to delete the order
    async function deleteOrder(orderID) {
        fetch(`{% url 'main:delete_order_ajax' 0 %}`.replace('0', orderID), {
            method: "POST"
        })
        .then((response) => {
            if (response.ok) {
                loadOrders();
                showAlert("Successfully deleted. Please check your orders.")
            } else {
                showAlert("Delete failed. Please try again.");
            }
        })
        .catch((error) => {
            console.error("Error while deleting order:", error);
            showAlert("Delete failed. Please try again.");
        });
    }

    //Function to show delete confirmation modal
    async function showConfirmationModal(orderID) {
        document.getElementById("confirmDelete").setAttribute("data-order-id", orderID);

        document.getElementById("confirmDelete").addEventListener("click", function() {
            const orderID = this.getAttribute("data-order-id");
            deleteOrder(orderID);
        });

        const confirmationModal = new bootstrap.Modal(document.getElementById('confirmationModal'));
        confirmationModal.show();
    }

    //Function to save edited order
    async function saveEditedOrder(orderID) {
        var amount = $('#editAmount').val();
        $.ajax({
            type: "POST",
            url: "{% url 'main:edit_order_ajax' 0 %}".replace('0', orderID),
            data: {
                amount: amount,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function(data) {
                loadOrders(); // Reload orders after edit
                showAlert("Order updated successfully!");
            },
            error: function(error) {
                showAlert("Error updating order.");
            }
        });
    }

    // Function to show edit modal
    async function showEditModal(orderID) {
        document.getElementById("confirmChanges").setAttribute("data-order-id", orderID);

        document.getElementById("confirmChanges").addEventListener("click", function(){
            const orderID = this.getAttribute("data-order-id");
            saveEditedOrder(orderID);
        });

        const editModal = new bootstrap.Modal(document.getElementById('editModal'));
        editModal.show();
    }

    // Function to calculate the total amount
    function calculateTotalAmount(orders) {
        var totalAmount = 0;
        for (var i = 0; i < orders.length; i++) {
            var order = orders[i];
            var foodPrice = parseFloat(order.fields.food_price);
            var amount = parseFloat(order.fields.amount);
            totalAmount += foodPrice * amount;
        }
        return totalAmount.toFixed(2);
    }

    // Function to show the payment modal
    async function showPaymentModal() {
        $.get("{% url 'main:get_product_json' %}", function(data) {
            var orders = JSON.parse(data);
            var totalAmount = calculateTotalAmount(orders);
            $('#totalAmount').text("$" + totalAmount);

            const paymentModal = new bootstrap.Modal(document.getElementById('paymentModal'));
            paymentModal.show();
        });
    }

    // Function to delete all orders
    async function deleteAllOrders() {
        fetch("{% url 'main:delete_allorder_ajax' %}", {
            method: "POST"
        })
        .then((response) => {
            if (response.ok) {
                loadOrders();
                showAlert("Payment successful! Thank you for coming here, please come back again!");
            } else {
                showAlert("Payment failed. Please try again.");
            }
        })
        .catch((error) => {
            console.error("Error while processing payment:", error);
            showAlert("Payment failed. Please try again.");
        });
    }

    document.getElementById("confirmPayment").addEventListener("click", function() {
        deleteAllOrders();
    });


</script>
{% endblock %}

main/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<section id="signup">
    <div class="w-5/6 my-6 mx-auto p-6 rounded-xl" style="background-color: #EAEFD3;">
        <h1 class="mb-6 text-3xl">Sign up</h1>
    
        <form method="POST" action=".">
            {% csrf_token %}
    
            <div class="mb-3">
                <label class="inline-block mb-2">Status:</label><br>
                {{ form.status }}
            </div>
    
            <div class="mb-3">
                <label class="inline-block mb-2">Full Name</label><br>
                {{ form.full_name }}
            </div>
    
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
    
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
    
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>
    
            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br>
                {{ form.password2 }}
            </div>
    
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
    
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
    
            <a class="text-lg">Already have an account?</a>
            <a class="underline text-lg text-blue-700" href="{% url 'main:login' %}">Log in</a>
            <br>
    
            <button id="submitbutton" class="my-2 py-4 px-8 text-lg rounded-xl">Submit</button>
        </form>
    </div>
</section>

<style>
    #signup {
        background-color: #FDFCF8;
    }
    #submitbutton {
        background-color: #2B6329;
        color: #FDFCF8;
    }
    #submitbutton:hover {
        background-color: #448941;
    }
</style>
{% endblock %}